AWSTemplateFormatVersion: 2010-09-09
Description: Create additional AWS resources for project
Parameters:
  CWProject:
    Description: "Cloud Workbench: Unique application/project name, used for resource naming and tagging (tr:service-name)."
    Type: String
  CWEnvName:
    Description: "Cloud Workbench: Environment's full name, typically in a form of '<team>-<sub-env>', used for resource naming and tagging (tr:service-name)."
    Type: String
  CWEnvType:
    Description: "Cloud Workbench: Environment type, used for tagging (tr:tr:environment-type)."
    Type: String
    Default: DEVELOPMENT
    AllowedValues:
      - DEVELOPMENT
      - INTEGRATION TESTING
      - QUALITY ASSURANCE
      - PRE-PRODUCTION
      - PRODUCTION
  CWAssetId:
    Description: "Cloud Workbench: Environment's associated AssetInsight ID, used for resource naming and tagging (tr:application-asset-insight-id)."
    Type: String
  CWCostCenter:
    Description: "Cloud Workbench: Environment's associated cost center, used for tagging (tr:financial-identifier)"
    Type: String
  CWOwnerEmail:
    Description: "Cloud Workbench: Environment's administrator email or distribution list, used for tagging (tr:resource-owner)."
    Type: String
  CWRegion:
    Description: "Cloud Workbench: Environment's deployment AWS Region."
    Type: String
  CWAwsAccId:
    Description: "Cloud Workbench: Environment's deployment AWS Account ID."
    Type: String
  CWVpcId:
    Description: "Cloud Workbench: Environment's deployment AWS VPC ID."
    Type: String
  CWDomain:
    Description: "Cloud Workbench: Environment's domain name registered in Route53."
    Type: String
  CWS3Bucket:
    Description: "Cloud Workbench: Environment's associated S3-bucket."
    Type: String

Resources:
  # sample task role, granting access to the CW's s3 bucket (restricted to specific path)
  HelloTaskIamRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: !Sub a${CWAssetId}-${CWEnvName}-ecs_task-${CWProject}-role
      Path: /service-role/
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/tr-permission-boundary'
      Policies:
        - PolicyName: !Sub a${CWAssetId}-${CWEnvName}-${CWProject}-policy-s3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:*'
                Resource:
                  - !Sub "arn:aws:s3:::${CWS3Bucket}/data/test/*"
              - Effect: Allow
                Action:
                  - 's3:ListBucket*'
                Resource:
                  - !Sub "arn:aws:s3:::${CWS3Bucket}"
             