default_context:
  project_name: 'iSplit_Backend'
  project_slug: 'isplit_backend'
  domain_main: 'dennis-mo.com'
  domain_staging: 'stag.dennis-mo.com'
  docker_swarm_stack_name_main: 'dennis-mo-com'
  docker_swarm_stack_name_staging: 'stag-dennis-mo-com'
  secret_key: '1185fb62249fcaff238a4ef287ed6ee2146e203dfce1de30360fa610c0357715'
  first_superuser: 'dennismoyunfei@gmail.com'
  first_superuser_password: 'Evangelion0306'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.dennis-mo.com", "https://stag.dennis-mo.com", "https://dennis-mo.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@dennis-mo.com'
  postgres_password: 'Evangelion0306'
  pgadmin_default_user: 'dennismoyunfei@gmail.com'
  pgadmin_default_user_password: 'Evangelion0306'
  traefik_constraint_tag: 'dennis-mo.com'
  traefik_constraint_tag_staging: 'stag.dennis-mo.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Evangelion0306'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
